# Generated by Django 2.2.5 on 2019-09-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
        ('core', '0002_auto_20190929_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='recursos',
            field=models.ManyToManyField(to='recursos.Recursos'),
        ),
    ]
